### ISSUE TITLE
auto update of HTML window

### ISSUE THREAD

**Issue by greg7mdp** [RickStrahl/Pandoc-MarkdownMonster-Addin#3]
Hi,

I installed Markdown Monster and this addin, and I have pandoc installed as well. After I add the addin to MarkDown Monster, I am able to select `Pandoc Markdown Parser` instead of `MarkDig` at the bottom, however changes I make to the markdown documents are not reflected in the HTML window on the right hand side (this works fine when using `MarkDig`).

Any idea?

**Comment by RickStrahl** [comment]
Hmmm... interesting. I see the same behavior. 

PanDoc doesn't have all the features of Markdig so a few important things like line matching unfortunately doesn't work which prevents the preview scroll syncing to work. However, it should definitely **refresh** the preview which is not happening.

I'll take a look.

**Comment by greg7mdp** [comment]
Thanks, Rick, glad it isn't just me :-)

**Comment by RickStrahl** [comment]
Fixed.

Looks like PanDoc is throwing a number of new warnings that was causing the add-in to not render output. Should be working now with the latest update in the Addin-Manager.

**Comment by greg7mdp** [comment]
Many thanks, works great now!
